---
kind: pipeline
type: docker
name:
steps:
  - name: tagging
    image: alpine
    commands:
      - echo -n "${DRONE_COMMIT_REF},latest" | awk -F "-v" '{print $NF}' > .tags
  - name: Build electron-packager
    image: plugins/docker
    settings:
      dry_run: true
      username:
        from_secret: dh_login
      password:
        from_secret: dh_pass
      repo: lizheming/drone-electron-packager
      dockerfile: Dockerfile
      context: electron-packager